// <auto-generated />
using System;
using DogDatabase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DogDatabase.Migrations
{
    [DbContext(typeof(DogContext))]
    [Migration("20210520174553_PopulateDogs")]
    partial class PopulateDogs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DogDatabase.Models.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short?>("Age")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Breed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Dog");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = (short)11,
                            Birthday = new DateTime(2010, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Breed = "Havanese",
                            Name = "Treasure",
                            Weight = 10f
                        },
                        new
                        {
                            Id = 2,
                            Age = (short)6,
                            Birthday = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Breed = "Shih Tzu",
                            Name = "Teegan",
                            Weight = 16f
                        },
                        new
                        {
                            Id = 3,
                            Age = (short)13,
                            Birthday = new DateTime(2008, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Breed = "Golden Retriever",
                            Name = "Declan",
                            Weight = 80f
                        },
                        new
                        {
                            Id = 4,
                            Age = (short)11,
                            Birthday = new DateTime(2009, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Breed = "Chihuahua-Toy Poodle Mix",
                            Name = "Cloe",
                            Weight = 7f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
